--- 
title: "Introduction to Time Series"
author: "Jean-Paul Renne"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 12pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This course XXX."
css: "my-style.css"
---


<!-- Declare new latex code: -->
\newcommand{\bv}[1]{\mathbf{#1}} 

# Introduction to Time Series {#intro .unlisted .unnumbered}

<!-- # Before starting {#intro .unlisted .unnumbered} -->

Time series constitute a prevalent data type in several disciplines, notably macroeconomics and finance. The modeling of time series is crucial for many purposes, including forecasting, understanding macroeconomic mechanisms, and risk assessment. This course proposes an introduction to time series analysis. It has been developed by [Jean-Paul Renne](https://www.jprenne.com) and [Alain Monfort](https://faculty.crest.fr/amonfort/).

Codes associated with this course are part of the `AEC` package, which is available on GitHub. To load a  package from GitHub, you need to use function `install_github` from the `devtools` package:

```{r installAEC, eval=FALSE}
install.packages("devtools") # in case you do not have that one.
library(devtools)
install_github("jrenne/AEC")
library(AEC)
```

**Useful (R) links:**

* Download R:

    *	R software: https://cran.r-project.org (the basic R software)
    *	RStudio: https://www.rstudio.com (a convenient R editor)

* Tutorials:

    *	Rstudio: https://dss.princeton.edu/training/RStudio101.pdf (by Oscar Torres-Reyna)
    *	R: https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf (by Emmanuel Paradis)
    * My own tutorial: https://jrenne.shinyapps.io/Rtuto_publiShiny/


<!-- <!-- To specify the corresponding covariance matrix vcov. to be used, there are three possibilities: 1. It is pre-computed and supplied in argument vcov.. 2. A function for extracting the covariance matrix from x is supplied, e.g., sandwich, vcovHC, vcovCL, or vcovHAC from package sandwich.  -->
<!-- ```{r shp2,warning=FALSE,message=FALSE} -->
<!-- library(AEC) -->
<!-- library(sandwich) -->
<!-- shp$income <- shp$i19ptotn/1000 -->
<!-- shp$female <- 1*(shp$sex19==2) -->
<!-- eq <- lm(income ~ edyear19 + age19 + I(age19^2) + female,data=shp) -->
<!-- #eq <- lm(income ~ edyear19 + age19 + I(age19^2) + female + I(female*ownkid19*(age19<40)),data=shp) -->
<!-- #lmtest::coeftest(eq,vcov. = sandwich) -->
<!-- #lmtest::coeftest(eq,vcov. = vcovHC) -->
<!-- #X <- cbind(1,shp$edyear19,shp$age19,shp$age19^2,shp$female) -->
<!-- #solve(t(X) %*% X) %*% t(X) %*% diag(eq$residuals^2) %*% X %*% solve(t(X) %*% X) -->
<!-- #vcovHC(eq,type="HC0") -->
<!-- #sandwich(eq) -->
<!-- #vcovHC(eq,type="HC1") -->
<!-- ``` -->
<!-- XXXX HC0, HC1... Davidson MacKinnon 2004 Section 5.5 XXXX -->

<!-- **p.d.f. version**: [here](https://www.dropbox.com/s/td4bqpbzfuvwsev/ApplEcts.pdf?dl=0). -->




